#配置端口号
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

spring:
#配置mysql数据源
  datasource:
    mysql:
#     指定主数据源  ?useUnicode=true&characterEncoding=utf8 防止汉字乱码
      primary: true
      name: report
      url: jdbc:mysql://127.0.0.1:3306/longhui?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      #数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项则下面三项配置无用
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#配置oracle 数据源
    oracle:
      jdbc-url: jdbc:oracle:thin:@localhost:1521/orcl
      username: admin
      password: admin
      driver-class-name: oracle.jdbc.OracleDriver

 #  redis配置
  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: root123456
    # 连接超时时间（毫秒）
    timeout: 30
    # 连接池中的最大连接数
    poolMaxTotal: 10
    # 连接池中的最大空闲连接
    poolMaxIdle: 10
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    poolMaxWait: 3
# mvc日期格式化
  mvc:
    date-format: yyyy-MM-dd
# thymeleaf缓存设置
  thymeleaf:
    cache: false
#配置国际化
  messages:
    basename: i18n.login
# rabbitmq配置
  rabbitmq:
    host: localhost
    username: guest
    password: guest
  #配置文件传输
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      maxFileSize: 100MB
      maxRequestSize: 100MB

# 邮件配置
  mail:
    host: smtp.qq.com
    username: 1608550717@qq.com
    password:
    default-encoding: UTF-8
mail:
  fromMail:
    addr: 1608550717@qq.com

#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboot.entity
#pageHelper 分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true




